### ISSUE TITLE
Question on usage on Gateway

### ISSUE THREAD

**Issue by JulianFeinauer** [eclipse/ditto-clients#40]
This is rather a question than an Issue but nonetheless I just post it here.
We are using Apache PLC4X in our java based application (plc4x.apache.org) which could, at the same time serve as Gateway in Eclipse IoT Terminology. So this would be the "client" which identifies with the "thing".
Is the Java Client right for this use case?
And if so, how do I correctly use the "client.live()" functionality? I did not fully get it from the documentation.

Thanks!
Julian

**Comment by thjaeckle** [comment]
Hi Julian.

Strictly speaking devices would not directly connect to Eclipse Ditto, but for example via Eclipse Hono or an MQTT broker which is capable of connecting millions of devices.
For gateway scenarios gateways could directly connect via WebSocket (which the Ditto Java client makes use of) to Ditto, so the client should be the right tool, yes.

Now there are two "channels" in Ditto, [twin and live](https://www.eclipse.org/ditto/protocol-twinlive.html).<br/>
In short:
* twin is for updating the persistence Ditto tracks of connected things
* live is for directly routing to connected devices without affecting Ditto's persistent view

## Twin
You can let your gateway just use the "twin" channel e.g. in order to react on changes done to persisted things (register for events/changes via the API).

And you can let the gateway update the persisted things via the "twin" channel, e.g. whenever a connected device updated a property in order to reflect that change in Ditto's persistence.

## Live
When using the `client.live()` you get an API for handling "live commands" (which e.g. another Java client acting as backend can create).
So your gateway would e.g. be able to react on "attribute modifications" by adding a callback via
```java
client.live().handleModifyAttributeCommands(...
```

The backend client would "issue" such a command by doing:
```java
client.live().forId(ThingId.of("foo:bar"))).putAttribute("hello", "world");
```
I hope that helps - I don't exactly fully grasp what your use case is - requiring either "twin" or "live" channel.
The Java Client docs by the way are mainly its Javadoc .. 
We some additional examples here: https://github.com/eclipse/ditto-examples/tree/master/java-client/src/main/java/org/eclipse/ditto/examples

**Comment by JulianFeinauer** [comment]
Thank you for the detailed reply @thjaeckle and indeed it makes some things clearer.
I saw in the code that the Client currently only supports WebSockets so this indeed is a showstopper for us as well (we usually use MQTT as Transport Layer).
And I got everything working nicely with the `client.twin()` but strugled with an example for `client.live()` (with property changes). I will retry it with your code given and come back if still have issues!

**Comment by yufei-cai** [comment]
@JulianFeinauer Keep in mind that Ditto is not an MQTT broker. To use MQTT as transport, you will need to bring your own MQTT broker and configure the Ditto back-end to talk to it.

Should you wish to work on adding MQTT support to the Java client, please let me know. It will become easier after #53 barring caveats (MQTT messages are binary; client and back-end need 2 topics for duplex communication).

**Comment by JulianFeinauer** [comment]
@yufei-cai thanks for the pointer. Indeed I am considering the additon of MQTT as provider. I understand that WebSockets is easier and "self-contained" but in many real world scenarios you want to have some kind of gateway pushing messages via message based communication (MQTT, AMQP, generally Hono, ...). So I see the need for that.
